version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lastest_news_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: lastest_news
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_password
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "15432:5432"
    volumes:
      # Thư mục trên host để lưu dữ liệu PostgreSQL
      - /mnt/drive2/lastest_news:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_user -d lastest_news"]
      interval: 10s
      timeout: 5s
      retries: 5

