version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: ba_crawler
    restart: unless-stopped
    environment:
      POSTGRES_USER: crawl
      POSTGRES_PASSWORD: crawl
      POSTGRES_DB: lastest_news
    ports:
      - "15432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
